Fixing the host-configs?

diff --git a/.github/workflows/ci_tests.yml b/.github/workflows/ci_tests.yml
--- a/.github/workflows/ci_tests.yml
+++ b/.github/workflows/ci_tests.yml
@@ -26,6 +26,7 @@ jobs:
         # We do not rely on the `github.event.pull_request.labels` information since it's cached at the job.
         # Changing labels or assignee in the PR would not allow to simply re-run the job with a different outcome.
         pr_json=$(curl -H "Accept: application/vnd.github+json" https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }})
+        if [[ $? -gt 0 ]]; then echo "Error during the curl process"; exit 1; fi
         draft_status=$(echo ${pr_json} | jq '.draft')
         echo "Draft status of PR is ${draft_status}."
         if [[ $draft_status == true ]]; then exit 1 ; fi
